server:
  port: 8087

spring:
  application:
    name: notification-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db?currentSchema=notification_schema
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notification_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info