server:
  port: 8082

spring:
  application:
    name: product-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db?currentSchema=product_schema
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: product_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  service-urls:
    user: http://localhost:8081
    product: http://localhost:8082
    inventory: http://localhost:8083
    cart: http://localhost:8084
    order: http://localhost:8085
    payment: http://localhost:8086

management:
  endpoints:
    web:
      exposure:
        include: health,info